//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMonitoring.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMonitoring.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar graph.
        /// </summary>
        public static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated.
        /// </summary>
        public static string Calculated {
            get {
                return ResourceManager.GetString("Calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated.
        /// </summary>
        public static string CalculatedData {
            get {
                return ResourceManager.GetString("CalculatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during create or update data..
        /// </summary>
        public static string CreateOrUpdateError {
            get {
                return ResourceManager.GetString("CreateOrUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during delete..
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete, there is a relationship with another object..
        /// </summary>
        public static string DeleteImpossibleBecauseRelationship {
            get {
                return ResourceManager.GetString("DeleteImpossibleBecauseRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE or UPDATE are not allowed in the query..
        /// </summary>
        public static string DeleteOrUpdateNotAllowedError {
            get {
                return ResourceManager.GetString("DeleteOrUpdateNotAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Div {
            get {
                return ResourceManager.GetString("Div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during duplication..
        /// </summary>
        public static string DuplicateError {
            get {
                return ResourceManager.GetString("DuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie chart.
        /// </summary>
        public static string EasyPieChart {
            get {
                return ResourceManager.GetString("EasyPieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge.
        /// </summary>
        public static string Gauge {
            get {
                return ResourceManager.GetString("Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retrieving data. .
        /// </summary>
        public static string GetError {
            get {
                return ResourceManager.GetString("GetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect syntax..
        /// </summary>
        public static string IncorrectSyntaxError {
            get {
                return ResourceManager.GetString("IncorrectSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure query.
        /// </summary>
        public static string IndicatorData {
            get {
                return ResourceManager.GetString("IndicatorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        public static string MaskData {
            get {
                return ResourceManager.GetString("MaskData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal multiple table.
        /// </summary>
        public static string MultiHorizontalTable {
            get {
                return ResourceManager.GetString("MultiHorizontalTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical multiple table.
        /// </summary>
        public static string MultiVerticalTable {
            get {
                return ResourceManager.GetString("MultiVerticalTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Auth.
        /// </summary>
        public static string NoAuth {
            get {
                return ResourceManager.GetString("NoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was not found..
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Auth 2.0.
        /// </summary>
        public static string OAuth20 {
            get {
                return ResourceManager.GetString("OAuth20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar.
        /// </summary>
        public static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slippery time.
        /// </summary>
        public static string SlipperyTime {
            get {
                return ResourceManager.GetString("SlipperyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string TargetData {
            get {
                return ResourceManager.GetString("TargetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during connection test..
        /// </summary>
        public static string TestConnectionError {
            get {
                return ResourceManager.GetString("TestConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range.
        /// </summary>
        public static string TimeRange {
            get {
                return ResourceManager.GetString("TimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Measure.
        /// </summary>
        public static string TitleIndicator {
            get {
                return ResourceManager.GetString("TitleIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transposition.
        /// </summary>
        public static string TranspositionColumnData {
            get {
                return ResourceManager.GetString("TranspositionColumnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single table.
        /// </summary>
        public static string UniqueTable {
            get {
                return ResourceManager.GetString("UniqueTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query returns an incorrect column name. Valid column name: VALUE, GROUP1, GROUP2, GROUP3, GROUP4, GROUP5..
        /// </summary>
        public static string WrongGroupColumnNameForFlowIndicator {
            get {
                return ResourceManager.GetString("WrongGroupColumnNameForFlowIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
